# Generated by Django 2.1.2 on 2019-04-15 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('customer_id', 'created_at')},
        ),
    ]
