# Generated by Django 2.1.2 on 2019-04-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190414_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='quantity',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
    ]
