# Generated by Django 2.1.2 on 2018-10-05 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountbalance',
            options={'verbose_name': 'Saldo de Cuenta Corriente', 'verbose_name_plural': 'Saldos de Cuenta Corriente'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitems',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items de Facturas'},
        ),
        migrations.AlterModelOptions(
            name='invoices',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
