# Generated by Django 2.1.2 on 2018-10-11 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20181011_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código de Pedido')),
                ('date', models.DateField(verbose_name='Fecha del Pedido')),
                ('discount', models.FloatField(help_text='%', verbose_name='Descuento')),
                ('shipping', models.CharField(choices=[('ENV', 'Envío'), ('REL', 'Retiro en Local')], max_length=3, verbose_name='Tipo de Envío')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('quantity', models.FloatField(verbose_name='Cantidad')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Order', verbose_name='Código de Pedido')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Products', verbose_name='Código de Producto')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items de Pedidos',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('status', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Estado')),
                ('sort', models.IntegerField(verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Estado de Pedidos',
                'verbose_name_plural': 'Estado de Pedidos',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('payment', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Método de Pago')),
                ('sort', models.IntegerField(verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Métodos de Pago',
                'verbose_name_plural': 'Métodos de Pago',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PaymentMethods'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.OrderStatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
