# Generated by Django 2.1.2 on 2018-10-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_csvfilesdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvfilesdata',
            options={'verbose_name': 'Archivos CSV', 'verbose_name_plural': 'Archivos CSV'},
        ),
        migrations.AlterField(
            model_name='csvfilesdata',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última modificación'),
        ),
    ]
