# Generated by Django 2.1.2 on 2019-03-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190307_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='related_cel_phone',
            field=models.CharField(default='-', max_length=15, verbose_name='Celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='related_city',
            field=models.CharField(default='-', max_length=80, verbose_name='Localidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='related_customer_address',
            field=models.CharField(default='-', max_length=150, verbose_name='Dirección del Comercio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='related_customer_name',
            field=models.CharField(default='-', max_length=150, verbose_name='Nombre del Comercio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='related_last_name',
            field=models.CharField(default='-', max_length=120, verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='related_name',
            field=models.CharField(default='-', max_length=120, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='related_telephone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='related_zip_code',
            field=models.CharField(default='-', max_length=15, verbose_name='Código Postal'),
            preserve_default=False,
        ),
    ]
