# Generated by Django 2.1.2 on 2018-10-05 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(verbose_name='Saldo Final')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Código de Cliente')),
                ('cuit', models.CharField(max_length=11, verbose_name='CUIT')),
                ('first_name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=80, verbose_name='Apellido')),
                ('zip_code', models.IntegerField(verbose_name='Código Postal')),
                ('telephone', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('discount', models.FloatField(help_text='%', verbose_name='Descuento')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('quantity', models.FloatField(verbose_name='Cantidad')),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Número de Factura')),
                ('date', models.DateField(verbose_name='Fecha de Factura')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código de Producto')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('brand', models.CharField(max_length=80, verbose_name='Marca')),
                ('product_line', models.CharField(max_length=80, verbose_name='Rubro')),
                ('unit', models.CharField(max_length=50, verbose_name='Unidad de Medida')),
                ('price', models.FloatField(verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('VEN', 'Vendedor'), ('CMA', 'Cliente Mayorista'), ('CMI', 'Cliente Minorista')], max_length=3, verbose_name='Tipo de Usuario')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer', verbose_name='Cliente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='invoice_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Invoices', to_field='number', verbose_name='Número de Factura'),
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Products', verbose_name='Código de Producto'),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer', verbose_name='Cliente'),
        ),
    ]
