# Generated by Django 2.1.2 on 2019-05-09 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(default='FA', max_length=2, verbose_name='Tipo de Comprobante')),
                ('invoice_branch', models.CharField(default='1', max_length=4, verbose_name='Sucursal')),
                ('invoice_number', models.CharField(default='1', max_length=8, verbose_name='Número')),
                ('product_id', models.CharField(max_length=20, verbose_name='Código de Producto')),
                ('price', models.FloatField(default=0.0, verbose_name='Precio')),
                ('quantity', models.FloatField(default=0.0, verbose_name='Cantidad')),
                ('amount', models.FloatField(default=0.0, verbose_name='Importe')),
                ('product_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción del Producto')),
            ],
            options={
                'verbose_name_plural': 'Items de Facturas',
                'verbose_name': 'Item',
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('invoice_id', models.CharField(default='FA-1-1', max_length=20, primary_key=True, serialize=False, verbose_name='Número de Factura')),
                ('invoice_type', models.CharField(default='FA', max_length=2, verbose_name='Tipo de Comprobante')),
                ('invoice_branch', models.CharField(default='1', max_length=4, verbose_name='Sucursal')),
                ('invoice_number', models.CharField(default='1', max_length=8, verbose_name='Número')),
                ('date', models.DateField(verbose_name='Fecha de Factura')),
                ('iva', models.FloatField(default=0.0, verbose_name='IVA')),
                ('taxes', models.FloatField(default=0.0, verbose_name='Percepciones')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name_plural': 'Facturas',
                'verbose_name': 'Factura',
            },
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='invoice_id',
            field=models.ForeignKey(default='FA-1-1', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.Invoices', verbose_name='Número de Factura'),
        ),
    ]
