# Generated by Django 2.1.2 on 2018-10-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181011_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStates',
            fields=[
                ('state', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Estado')),
                ('order', models.IntegerField(verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Estado de Pedidos',
                'verbose_name_plural': 'Estados de Pedidos',
            },
        ),
    ]
