# Generated by Django 2.1.2 on 2019-06-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_productimages_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación / Actualización'),
        ),
    ]
