# Generated by Django 2.1.2 on 2018-10-24 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181016_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name': 'Item de Pedido', 'verbose_name_plural': 'Items de Pedidos'},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_type',
            field=models.CharField(blank=True, choices=[('VEN', 'Vendedor'), ('CMA', 'Cliente Mayorista'), ('CMI', 'Cliente Minorista'), ('ADM', 'Administrador')], max_length=3, null=True, verbose_name='Tipo de Usuario'),
        ),
    ]
