# Generated by Django 2.1.2 on 2018-10-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181023_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=150, verbose_name='Dirección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='', max_length=80, verbose_name='Localidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default='', max_length=50, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='', max_length=120, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='cuit',
            field=models.CharField(max_length=11, verbose_name='CUIT / DNI'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Código de Cliente'),
        ),
    ]
