# Generated by Django 2.1.2 on 2018-10-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181030_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFilesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=15, verbose_name='Archivo')),
                ('modified_date', models.DateTimeField(verbose_name='Última modificación')),
            ],
        ),
    ]
