# Generated by Django 2.1.2 on 2019-03-07 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20181109_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Comprobante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='voucher',
            field=models.CharField(default='FC A 0000-00000000', max_length=30, verbose_name='Comprobante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='products',
            name='offer',
            field=models.BooleanField(default=False, help_text='El Producto esta en oferta?', verbose_name='Oferta'),
        ),
        migrations.AddField(
            model_name='products',
            name='offer_price',
            field=models.FloatField(default=0, verbose_name='Precio Oferta'),
        ),
        migrations.AddField(
            model_name='products',
            name='package',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Envase'),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='balance',
            field=models.FloatField(verbose_name='Saldo'),
        ),
        migrations.AlterUniqueTogether(
            name='accountbalance',
            unique_together={('customer_id', 'date', 'voucher')},
        ),
    ]
