# Generated by Django 2.1.2 on 2019-03-13 19:48

import app.models
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190311_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, max_length=200, quality=0, size=[200, 200], upload_to=app.models.product_image_path)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Products', verbose_name='Cliente')),
            ],
        ),
    ]
