# Generated by Django 2.1.2 on 2019-03-15 14:59

import app.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190313_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, max_length=200, null=True, quality=0, size=[200, 200], upload_to=app.models.product_image_path, verbose_name='Imágen'),
        ),
    ]
